---

# Variables:
#
# - freshclam_checks, defaults to 24, restricted in this role to [1..48].

- name: Check OS family
  ansible.builtin.assert:
    that: ansible_facts['os_family'] == 'Debian'
    fail_msg: "This role is implemented only for Debian OS family !"
    quiet: true

- name: Check freshclam_checks variable
  ansible.builtin.assert:
    that:
      - freshclam_checks is number and freshclam_checks is integer
      - freshclam_checks > 0 and freshclam_checks < 49
    fail_msg: "freshclam_checks must be an integer between 1 and 48 !"
    quiet: true

- name: Install clamav
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - clamav
      - clamav-freshclam
    state: present

- name: The freshclam service should be enabled and running
  become: true
  become_user: root
  ansible.builtin.service:
    name: clamav-freshclam.service
    enabled: yes
    state: started

- name: Set freshclam's number of checks per day
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/clamav/freshclam.conf
    regexp: "^Checks "
    line: "Checks {{ freshclam_checks }}"
  notify:
    - Restart freshclam
