---

# Variables:
#
# - freshclam_checks, defaults to 24

- name: Install clamav
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - clamav
      - clamav-freshclam
    state: present

- name: The freshclam service should be enabled and running
  become: true
  become_user: root
  ansible.builtin.service:
    name: clamav-freshclam.service
    enabled: yes
    state: started

- name: Set freshclam's number of checks per day
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/clamav/freshclam.conf
    regexp: "^Checks "
    line: "Checks {{ freshclam_checks }}"
  notify:
    - Restart freshclam
