---

all:
  hosts:
    laptop1:
      ansible_host: 127.0.0.1
      ansible_connection: local
      host_apps:
        - curl
      userlist:
        - calin
        - tester
    laptop2:
      # ansible_host: mini.home.local
      ansible_host: 10.55.208.193
      userlist:
        - calin
    desktop1:
      # ansible_host: 192.168.100.5
      ansible_host: 10.55.208.193
      host_apps:
        - curl
      userlist:
        - calin
        - tester
    desktop2:
      ansible_host: 192.168.100.6
      userlist:
        - tester

  children:
    laptops:
      hosts:
        laptop1:
        laptop2:
    desktops:
      hosts:
        desktop1:
        desktop2:
