---

# Requirements: community.general
# Install the requirements with: `ansible-galaxy collection install community.general`
#
# Variables:
#
# x_user dictionary with these fields:
#   - name
#   - (optional) dconf dictionary:
#     - (optional) GTK_theme
#     - (optional) fixed_dock
#     - (optional) media_keys
#     - (optional) favorite_apps

- name: Verify x_user variable
  ansible.builtin.assert:
    that:
      - x_user is defined
      - x_user is not string
      - x_user is iterable
      - x_user is mapping
    fail_msg: "x_user dictionary must be defined !"
    quiet: true

- name: Verify required string variables
  ansible.builtin.assert:
    that:
      - x_user['name'] is defined
      - x_user['name'] != None
      - x_user['name'] | length > 0
    fail_msg: "x_user['name'] must be set !"
    quiet: true

- name: Configuration for dconf
  when: x_user['dconf'] is defined
  become: true
  become_user: "{{ x_user['name'] }}"
  block:

    - name: Set the GTK theme
      community.general.dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'{{ x_user['dconf']['GTK_theme'] }}'"
        state: present
      when: x_user['dconf']['GTK_theme'] is defined

    - name: Auto-hide the Dock
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
        value: "{% if x_user['dconf']['fixed_dock'] %}true{% else %}false{% endif %}"
        state: present
      when: x_user['dconf']['fixed_dock'] is defined

    - name: Set the shortcuts
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop: "{{ x_user['dconf']['media_keys'] | dict2items }}"
      when: x_user['dconf']['media_keys'] is defined

    - name: Set the list of favorite apps
      community.general.dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "{{ x_user['dconf']['favorite_apps'] }}"
        state: present
      when: x_user['dconf']['favorite_apps'] is defined
