---

- name: Get the key's value
  ansible.builtin.set_fact:
    current_val: "{{ imported_vscode_settings | community.general.json_query(query_str) }}"
  vars:
    query_str: '"{{ item.key }}"'

- name: Change the key's value
  ansible.builtin.set_fact:
    imported_vscode_settings: "{{ imported_vscode_settings | combine({item.key: item.value}) }}"
  when: current_val|string != item.value|string
