---

- name: Check OS family
  ansible.builtin.assert:
    that: ansible_facts['os_family'] == 'Debian'
    fail_msg: "This role is implemented only for Debian OS family !"
    quiet: true

- name: Add the signing key
  become: true
  become_user: root
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    state: present

- name: Add the repository
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/ms-teams stable main'
    filename: 'teams'
    state: present
    update_cache: true

- name: Install Teams
  become: true
  become_user: root
  ansible.builtin.apt:
    name: teams-insiders
    state: present
