---

- name: Install Podman prerequisites
  become_user: root
  ansible.builtin.package:
    name:
      - curl
      - gnupg
    state: present

- name: Select task file based on OS version
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ role_path }}/tasks/install-{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
        - "{{ role_path }}/tasks/install.yml"
