---

#
# Note: firewalld 'needs' iptables (? when? is just an alias now ? since when?) so do not remove iptables
#

- name: Install nftables and firewalld
  become: true
  become_user: root
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop:
    - nftables
    - firewalld

- name: Enable nftables and firewalld services
  become: true
  become_user: root
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - nftables.service
    - firewalld.service

- name: Select nftables as backend in firewalld
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: "^FirewallBackend="
    line: "FirewallBackend=nftables"
  notify:
    - Restart firewalld
