---

# Variables:
#   - kicad_version, default value '7.0'

- name: Add the KiCad repository
  become: true
  become_user: root
  ansible.builtin.apt_repository:
    repo: "ppa:kicad/kicad-{{ kicad_version }}-releases"
    state: present
    update_cache: yes

- name: Install KiCad
  become: true
  become_user: root
  ansible.builtin.apt:
    name: kicad
    state: present
    install_recommends: true
